name = "QuantumAnnealingAnalytics"
uuid = "f4de928d-7c93-4858-9dcf-40bc6948a1da"
authors = ["Zach Morrell, Carleton Coffrin"]
repo = "https://github.com/lanl-ansi/QuantumAnnealingAnalytics.jl"
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumAnnealing = "4832667a-bab9-40a8-88f6-be9efce3ea89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
